"$schema" = "https://raw.githubusercontent.com/durocodes/audit/main/schema.json"

[[solutions]]
day = 1
part1 = "984"
part2 = "5657"

[[solutions]]
day = 2
part1 = "40055209690"
part2 = "50857215650"

[[solutions]]
day = 3
part1 = "17278"
part2 = "171528556468625"

[[solutions]]
day = 4
part1 = "1518"
part2 = "8665"

[[solutions]]
day = 5
part1 = "623"
part2 = "353507173555373"

[[solutions]]
day = 6
part1 = "5316572080628"
part2 = "11299263623062"

[[solutions]]
day = 7
part1 = "1649"
part2 = "16937871060075"

[[solutions]]
day = 8
part1 = "69192"
part2 = "7264308110"

[[solutions]]
day = 9
part1 = "4755429952"
part2 = "1429596008"
